### ISSUE TITLE
Update the AUR package?

### ISSUE THREAD

**Issue by federicotorrielli** [jaltuna/refind-theme-nord#2]
Hello there,
First of all, I really love this theme, it's great!
Second, can you please update (or remember to do so for the next releases) the [AUR package](https://aur.archlinux.org/packages/refind-theme-nord)?

Thanks!

**Comment by jaltuna** [comment]
Hi Federico, 

This weekend I get with it.

Greetings!

**Comment by federicotorrielli** [comment]
Thanks, you can close this when you'll be done :D

**Comment by jaltuna** [comment]
Updated AUR
